apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ManifestIntegrityConstraint
metadata:
  annotations:
    cosign.sigstore.dev/bundle: H4sIAAAAAAAA/0STS4/iOhOG/0u2M9IX59YEaRZA4hBDQuP4gr1zYujcHOgGOpDR/PdPnDnS2b6lKlU9euq3VTQfw1HHw+3rSRpzvN6UuVhzK4v3qzSKvgP5g6+jxs8jOzwvuv89P99jFKgiHuPN53VTqBG5RNtg0SyCZlZg8bn7Xtzdablb/+Duu4y26dLrfOUNMFChKVN6gbf9r1/WT+tdPfuz0tb8t1We9dOaW8cnqquk5/KAJsXDe9qem2zljds2brYr9KW4370ylcBJJayrDPsqXdSlzdhU7rIXzzQ4PlEnDrhO28tbauq6cj6a3XBtBH8MpYsuOqlvrxmVU9dZS51Xrzbwqjltdk3q5FPs50a2klTjLpGdJH2fR7gTXBox5XU2IbMjC1sQXAsHm4x8eFmbusJgkzvUE4ZO0mQga6tpx2WbO7JJBxBuV6+b9F0cMKgM/buTE951wu56lQZpByCjOcJ9L/dOToq1dilEGxbBdwI1ksNyEs9bUIG83rG9jVc3ipOzww/L740rfB7DC6bQLYY65cPeLieNaczgjuffBZ8BmtQdpiCibb/BEZwyJyc7uPCqHjUSYvRepNd0WAJhHhdh3/pj8Q/LtnR8W3LffjEjMBt1/CAZzQvG8YYl/YoyyYoOEEbBQKcl592DZGuc0Wm5ZZCpyuxH1uYHxutMtHAsDLuVrsZZLAsG2JUk6aOKL33JQ5d2LKF9N9IeqSyWCenrUbPLHXeSHzs/58a/kl48NdSHIr64klI/hyggB01YLCXp4VhxFMs1yzIHC8HkmEMxqWhZFLH/lEwWHKIrMz7P+DhSwDzFc1i6qFbmMVHHT46MrXmXN3iKgbBxQThLab/sMaQPxjKfMc2LDu1ZtNz+x0NSBeDAqOR7gGEZY4QPOGHg3/oaR3Kyw5cHp4P9kr8ZbsePL3U76tfXWXMQBJ7ruG+h+9Pqzx/poI8Pa+4B4Aeh8zeKrLlV2dpxdaC0Zwfhm3sKfT88uaVyNKiUDU4zD3hvenY6VX458zy/chzvFM7K0A/BzAba+vPn/wEAAP//R7JhafMDAAA=
    cosign.sigstore.dev/message: H4sIAAAAAAAA/wArAtT9H4sIAAAAAAAA/+xTW0/jPBDtc3+FxeunUKdNuUTiodDAF2iBcgtltQ/GTIKb+ILtQoL2x68SQsgi7S5IK61W6nnJ+Ph4zsxo0rNc9ajkSoMxTCSOJdpJnp0B7W/HW6QP7tZWjxPBYjB2vSA863waGGO84XnVF2P8/ut63kbH9Qaut+niQd/t4L672d/oIPx5q89jaSzRHYy1lPZXut/dv2/uHwFR7Aq0YVL4iEphrCZMWLOeEAspgAK9bu57j+4tWOJ2UybufDSt1yEUFhLNbLHXPOxysOSOWOJ3ERKEg49AxFJTcPQyA8cQrjJwlJYxy8DBXaOAllpOLL0vA4RKE/MSOogodqDlUtXEC6VMc1hbq8PWq5Ifg8pkwUHYhjoH/cgoVOeyNKMIhcaorkyUqRXRhIMFXd8SassB1Zm4vHtrq+LeBnf8gZaraqEcWsySxj+F4tUAodNg6qNvzREhp8RucBAeo9PL3Um4h46CeUW2RNP99Cl4mv9/JG/C5wXeG83mYR2PRzM6niWjYPgs4ocgGkziYhqlV9da5Sf5wQCH7vWwlWqRbYreU8Ru8ii3Y5MWF9H+ZRLNbTi5VYf/Lbazwwd9Gu9mvFDeJLcn+XA4613Mz0Y7O+/LDo7HPy36IytS6uTtAqg9hwyoldpHX75WtGGJIHap4Qzi1+m1OCOXmrbvXg0bjaNr0Q+CajP81kr87b90hRVWWOHP43sAAAD//z9bFrQACgAAAQAA//9Xl7jNKwIAAA==
    cosign.sigstore.dev/signature: MEUCIFYYCcSHwwPRJT1OLWIfpsc+zsSa9T4D+TDj6Ypo+v9XAiEAwJxHZt4o7QPEE9coIo5PhdEMCR9JD1s3cS8P8rRbdTI=
  name: enforce-rule-sample-profile-0
spec:
  match:
    kinds:
    - apiGroups:
      - apps
      - ""
      kinds:
      - Deployment
      - Service
    namespaces:
    - sample-ns
  parameters:
    action:
      mode: enforce
    constraintName: enforce-rule-sample-profile-0
    keyConfigs:
    - key:
        PEM: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5znfqEW3LfyMWkVXrpxOxG30I1X5
          jl7n/wWiZxWxtDskyTWFUgWYtILbpJ+j9lJqrPfBlmyp4LxtOx55Q/TYRA==
          -----END PUBLIC KEY-----
        name: enforce-rule-sample-profile-0
    objectSelector: []
    signatureRef:
      signatureResourceRef:
        name: signature-resource
        namespace: sample-ns
