apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ManifestIntegrityConstraint
metadata:
  name: enforce-rule-sample-profile
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      - apps
      kinds:
      - ConfigMap
      - Deployment
    namespaces:
    - sample-ns
  parameters:
    action:
      mode: enforce
    constraintName: enforce-rule-sample-profile
    objectSelector:
    - name: sample-configmap
    - name: sample-deployment
