apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ManifestIntegrityConstraint
metadata:
  annotations:
    cosign.sigstore.dev/bundle: H4sIAAAAAAAA/0ST2a6jOBCG34XrlgazJIdIc3GSYI7pmATjJfgOMAmLIXuztPrdR5kz0tz+pSpVffrqt5HU575Ufv+8T7Tuyscz667GysA+26B4azN0PnBdZtH0+Yjhxor381/Nbdgm8/mGyZLle4fDUh68MzojuQbu9vVrkDc/3v8yT+793F6EE3nDcr8MxnsQoovuh1v8+bfxwzhkk75kylj9NvKLmoyVUU5hVQRayGM4Z8J7oeZS440z7Bq/3m3Ceybc9p1lAZyzgLdFx++5HbaoHurCXut0QotyCtv0SCrUXJeoq6rCOtf7/lGnYuxzO7yqoHq+ZxRWVeGGWe9e1cGHEqze16GO5vOALTzhLdFScJ1SNsjt54wD0koaTxH9HCOKbDxHbSpIl9LUiWalMf10JPXdfYBtTHmd0qqRTdRiEdaoB95u875JvdIjAUXHvneyvJcK+Ett0AK1AHIWhYzFJqEhUG0F4/rpp924ScF6F4unQ0B1ELX3kC2HTCNXztGBdhCVR3nHW2UnQh1yqm6pls89rUasr1es1wfCoKvsSu+DYY613v80gUn88MY1jONmfShmHh4S9ED9GqTdeE3Npy6Tf1k2ueWaUrjmmxmFeFD+SDGLEi7ITx7oDeOSJy2gnIGezWsh2pHiL4LZvN5xyLOiiwfeREcuKpw2cEg6/sxtRbAvEw74gwZoLPyrzoVns5YHTLcD02GGfRlQXQ2KX1+klaJs3Uh07oPqdFJQHRP/akvG3AiGC3pUlPtSUg2HQoS+/OIYWyRNuRwimM7Zdp0kvjtJLhMBwwfvXIHFMDDAnUxEMLfDKuvGmVluUHL+JdqoJrMPUpMkVHDE9FoTyEbOscu5Ekkbxny73v3PQ7IMwJ4zKWJAYO6TkBxJwMF/9S+ylbPpvT04Hc23/HX/LM/37Fmq99cZK7BYONbSsZf2D0NfzqhX5WisHHO59DzwHW2NlVGYyrLVIlOOufCW9slzXe9k55mlQJGZ4PThAGepPk6nws0/HMctLMs5eR+553rgwwTK+PPnnwAAAP//oOTPYvMDAAA=
    cosign.sigstore.dev/message: H4sIAAAAAAAA/wAqAtX9H4sIAAAAAAAA/+xT3U7jPBDtdZ/C4vZTqENTCpG4KDTwBVqg/IWy2gtjJsFN/IPtQoL24VcJIWSRdheklVYr9dxkfHw8Z2Y06VmuelRypcEYJhLHEu0kz06fbmzHW2QD3K2tHieCxWDsekF41vk0MMZ40/OqL8b4/df1vM2O6/Vdb+ANh3jQwRvu0PM6CH/e6vNYGkt0B2Mtpf2V7nf375v7R0AUuwJtmBQ+olIYqwkT1qwnxEIKoECvm/veo3sLlrjdlIk7H03rdQiFhUQzW+w1D7scLLkjlvhdhATh4CMQsdQUHL3MwDGEqwwcpWXMMnBw1yigpZYTS+/LAKHSxLyEDiKKHWi5VDXxQinTHNbW6rD1quTHoDJZcBC2oc5BPzIK1bkszShCoTGqKxNlakU04WBB17eE2nJAdSYu797aqri3wR1/oOWqWiiHFrOk8U+heDVA6DSY+uhbc0TIKbEbHITH6PRydxLuoaNgXpEt0XQ/fQqe5v8fyZvweYH3RrN5WMfj0YyOZ8koGDyL+CGI+pO4mEbp1bVW+Ul+0Mehez1opVpkQ9F7ithNHuV2bNLiItq/TKK5DSe36vC/xXZ2+KBP492MF8qb5PYkHwxmvYv52Whn533ZwfH4p0V/ZEVKnbxdALXnkAG1Uvvoy9eKNiwRxC41nEH8Or0WZ+RS0/bdq2GjcXQt+kFQbYbfWom//ZeusMIKK/x5fA8AAP//FFVprAAKAAABAAD//71TolsqAgAA
    cosign.sigstore.dev/signature: MEUCIQD4E2uvHEB+DblBcPKAkxGXOZ/lfEERR9g3ONaHyvk07wIgOm7jbVm98q2Zi2POEAywxe8l3BYN+MtDBjVQPB0Os5I=
  name: enforce-rule-sample-profile-0
spec:
  match:
    kinds:
    - apiGroups:
      - apps
      - ""
      kinds:
      - Deployment
      - Service
    namespaces:
    - sample-ns
  parameters:
    action:
      mode: enforce
    constraintName: enforce-rule-sample-profile-0
    keyConfigs:
    - key:
        PEM: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5znfqEW3LfyMWkVXrpxOxG30I1X5
          jl7n/wWiZxWxtDskyTWFUgWYtILbpJ+j9lJqrPfBlmyp4LxtOx55Q/TYRA==
          -----END PUBLIC KEY-----
        name: enforce-rule-sample-profile-0
    objectSelector: []
    signatureRef:
      signatureResourceRef:
        name: signature-resource
        namespace: sample-ns
