apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ManifestIntegrityConstraint
metadata:
  annotations:
    cosign.sigstore.dev/bundle: H4sIAAAAAAAA/0STS4+jOhOG/wvbb6TBgNMh0iyaxNDQsTNcbMfeASbhYmg6SQ+X0fz3TzlzpLN9S1WqevTUbyNtrkOl0PC4LVnTV/dH3o/GzsAo3ofeA9ArXMbkGhNv/v5ifyZi30R3Z8X6aF5Jcf1sr68aEnd4bbz5NkX3+dQE47WP1a8xbuhJr/Y+uaBz8X1A+n/fi+N5ruvs9ccP45vxM1/0R66M3W+j+FCLsTOqJarLQHN5jtacu19h+9HgvTMdW9Qc99Et57B7Znngr3nAurJnt8KOurCZmtL2tFjCTbVEnTgnddiOL2Ff16V1bU7DvRF8Hgo7GlVQP54zSquucUutZ6/q/bvitDk1oUPW0sY9hqRNGnJQrbBkcwrihaydKVpkkdbrSFvOoi1tYiW9PISAZKGF27omK7ZOga9JEM4kQI7MOiBWNIUDcI/7503qS5wTUPb0706W+6UC9qX24SbsgE8piVIkx7QXpli7X7HpojjdgqP1eCNMwVxLJqx5c8pUiG0SM9O8kaHuSaY/FfXHmIOsCuhc8frGlockQK1iqAkxxfpuwveidxwW+PgdxCZZYydto65kZK8ocn+m4T0cPCD6eRTmQ1fpPyzbwoKm5NB8Mst8PCk0Z5iSlPHknQV6T5lkaQcyRsFAV4/zbs7wW4Lp6h2Zz/KyjyfWkjPjNRatP6U9exS2SjCSKQPsngXhXKJRF9y1accCqruJ6ijHSAaZrifFxq+kk7zqIOE9vGdaLMpX5xSNtqQUEj/aZGeVMSRlpv2p5BGSbwxjKxGCyYn4Ys0PXpoiuEgmU+5Hd9ZDjvk0UcCcnBO/sKM67+eVWjCoGHvjHWmSFQFhJmnGWUi1pxOfzoxhyJjiaRfF7OAd/+MhaQ78gVHJY5D4BUqi5JwEDPxbf0sOcjXdpweXs/mUvxke1fWWPyr1/DpjBzYbx4Zbd2t+M/THNRxUNRs7BziWa7l/o4OxM0pTWbba5MoxN+6LfXEhdC92kVsKlLkJLlsHOC9qe7mUsNg6Diwty7m428KFLtiaQBl//vw/AAD//z6vs0nzAwAA
    cosign.sigstore.dev/message: H4sIAAAAAAAA/wAqAtX9H4sIAAAAAAAA/+xTW0/jPBDtc3+FxeunUKdNuUTiodDAF2iBcgtltQ/GTIKb+ILtQoL2x68SQsgi7S5IK61W6nnJ+Ph4zsxo0rNc9ajkSoMxTCSOJdpJnp0B7W/HW6QP7tZWjxPBYjB2vSA863waGGO84XnVF2P8/ut63kbH9QbuELtDF3sd3Hc3+14H4c9bfR5LY4nuYKyltL/S/e7+fXP/CIhiV6ANk8JHVApjNWHCmvWEWEgBFOh1c997dG/BErebMnHno2m9DqGwkGhmi73mYZeDJXfEEr+LkCAcfAQilpqCo5cZOIZwlYGjtIxZBg7uGgW01HJi6X0ZIFSamJfQQUSxAy2XqiZeKGWaw9paHbZelfwYVCYLDsI21DnoR0ahOpelGUUoNEZ1ZaJMrYgmHCzo+pZQWw6ozsTl3VtbFfc2uOMPtFxVC+XQYpY0/ikUrwYInQZTH31rjgg5JXaDg/AYnV7uTsI9dBTMK7Ilmu6nT8HT/P8jeRM+L/DeaDYP63g8mtHxLBkFw2cRPwTRYBIX0yi9utYqP8kPBjh0r4etVItsU/SeInaTR7kdm7S4iPYvk2huw8mtOvxvsZ0dPujTeDfjhfImuT3Jh8NZ72J+NtrZeV92cDz+adEfWZFSJ28XQO05ZECt1D768rWiDUsEsUsNZxC/Tq/FGbnUtH33athoHF2LfhBUm+G3VuJv/6UrrLDCCn8e3wMAAP//P9r/PAAKAAABAAD//+yrlnIqAgAA
    cosign.sigstore.dev/signature: MEQCIHFiJf4c9/CODA/5/kG5WyjVUclz97H3sPWM+6xf59juAiAmSxe1yhkW+Y7WsbxM7F3+NJnn8TaL+T4748J2dqSBuA==
  name: enforce-rule-sample-profile-0
spec:
  match:
    kinds:
    - apiGroups:
      - apps
      - ""
      kinds:
      - Deployment
      - Service
    namespaces:
    - sample-ns
  parameters:
    action:
      mode: enforce
    constraintName: enforce-rule-sample-profile-0
    keyConfigs:
    - key:
        PEM: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5znfqEW3LfyMWkVXrpxOxG30I1X5
          jl7n/wWiZxWxtDskyTWFUgWYtILbpJ+j9lJqrPfBlmyp4LxtOx55Q/TYRA==
          -----END PUBLIC KEY-----
        name: enforce-rule-sample-profile-0
    objectSelector: []
    signatureRef:
      signatureResourceRef:
        name: signature-resource
        namespace: sample-ns
