apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ManifestIntegrityConstraint
metadata:
  annotations:
    cosign.sigstore.dev/bundle: H4sIAAAAAAAA/0STS4+jOhOG/wvbGWkwl3SINIskXIK7TRqD7dg7g0m4N5OQj8to/vunnDnS2b6lKlU9euq3llS3vlBeP96XtOqKxyi7QdtpyIuP4f7TfRvCL6PjEEjxjZlzuRDHSDYg5n797A6PZ/y/sFRvot9X+zH79uPHthAJrGXLq+58J1P/rltrGWVUPm+/hrw8HwPltfufP7Xv2qdc2i+ptN1vLftSi7bTigWWedAycYGrZM4zrL8qdLSmj9qrPo7wLpndvDIZ+KsMaJN39J6ZsAmrqcrNQ8uXcFMssOEXXIb18BZ2ZZkbt+rcPyrO5j4z4aCCcnzNyI2yRDUxXr2q8x+KkepcwZobZOIMdjz1AHJFFxkcILesUBfPnCGbp7jm636KXFgiV3XcIPOZxTpfkXUOuHF24xW5bYXWHEQGrSKG5rAHzsfxdZN68gsGeUf+7mQ4TxXQpzqGm7ABPiURjFMfopWOyal9KhN7aeDERWOvhRvB9xXH+QXWqKaWqKP33OV3UYsxr8Wp8PwBE++euO1AuiHAINKjAC9nqurEEL+KkzrgoNFjomDE7DVntzU6tQMG+0UCZH0m4SPsD4B388D1sS2Sf1jWmWHrgtn6i1nqo0l5c4pIlFCG32nQHgkVNGlASgnoyXpgrJlTdMKIrIcP6lOZd/FE6+hCWYl47U9JR8fMVBh5IqGAPtIgnHNvaDPmmKShAWmbibRQIk8EaVtOig5P3AhWNHbEOvuRtnxRvrok3mAKQuzIh5v0olLqCZG2/pQz6IkTRcjAnFMxRT5fpXtIEs9eBBUJ8+GDdjZDbJoIoJZkkZ+ZsJTdvBLDDgpKT6yJKrx6gOs4SRkNSXtosU9mSpFNqWJJA2PqHj7+4yGIBH5PiWAxwH7mYYgvOKDg3/oJu2LVnZcH14v+kr/qx+J2l2OhXl+n7cBmY5n2xjSs71r7dQt7VczazgKm45jm38jVdlquK8NUG6ksfeO8mVfHtp2rmUlDgVzq4Lq1gPWmttdrbmdby7Jzw7CuzjZzbAdsdaC0P3/+HwAA//9M7g0v8wMAAA==
    cosign.sigstore.dev/message: H4sIAAAAAAAA/wApAtb9H4sIAAAAAAAA/+xT3U7jPBDtdZ/C4vZTqENTCpG4KDTwBVqg/IWy2gtjJsFN/IPtQoL24VcJIWSRdheklVYr9dxkfHw8Z2Y06VmuelRypcEYJhLHEu0kz06fbmzHW2QD3K2tHieCxWDsekF41vk0MMZ40/OqL8b4/df1vM2O6/XdAcbDYanbcIf9YQfhz1t9Hktjie5grKW0v9L97v59c/8IiGJXoA2TwkdUCmM1YcKa9YRYSAEU6HVz33t0b8ESt5syceejab0OobCQaGaLveZhl4Mld8QSv4uQIBx8BCKWmoKjlxk4hnCVgaO0jFkGDu4aBbTUcmLpfRkgVJqYl9BBRLEDLZeqJl4oZZrD2lodtl6V/BhUJgsOwjbUOehHRqE6l6UZRSg0RnVlokytiCYcLOj6llBbDqjOxOXdW1sV9za44w+0XFUL5dBiljT+KRSvBgidBlMffWuOCDkldoOD8BidXu5Owj10FMwrsiWa7qdPwdP8/yN5Ez4v8N5oNg/reDya0fEsGQWDZxE/BFF/EhfTKL261io/yQ/6OHSvB61Ui2woek8Ru8mj3I5NWlxE+5dJNLfh5FYd/rfYzg4f9Gm8m/FCeZPcnuSDwax3MT8b7ey8Lzs4Hv+06I+sSKmTtwug9hwyoFZqH335WtGGJYLYpYYziF+n1+KMXGravns1bDSOrkU/CKrN8Fsr8bf/0hVWWGGFP4/vAQAA///ZdKw7AAoAAAEAAP//f2Ni0ykCAAA=
    cosign.sigstore.dev/signature: MEUCIA1I35mHynwtDLoPzNsx3I+4Pqrc25xf3Jp6+f6mr6GxAiEA+H9iRjFGSt4dr9WcKfjxwADi4AGI5nsqh34yiGP2kS8=
  name: enforce-rule-sample-profile-0
spec:
  match:
    kinds:
    - apiGroups:
      - apps
      - ""
      kinds:
      - Deployment
      - Service
    namespaces:
    - sample-ns
  parameters:
    action:
      mode: enforce
    constraintName: enforce-rule-sample-profile-0
    keyConfigs:
    - key:
        PEM: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5znfqEW3LfyMWkVXrpxOxG30I1X5
          jl7n/wWiZxWxtDskyTWFUgWYtILbpJ+j9lJqrPfBlmyp4LxtOx55Q/TYRA==
          -----END PUBLIC KEY-----
        name: enforce-rule-sample-profile-0
    objectSelector: []
    signatureRef:
      signatureResourceRef:
        name: signature-resource
        namespace: sample-ns
