apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ManifestIntegrityConstraint
metadata:
  annotations:
    cosign.sigstore.dev/bundle: H4sIAAAAAAAA/0STS4/iOBCA/0uuM4c4DyBIe2jIA7uxaRI/sG9JHMibbJPuhIzmv6/YWWmP9ZWqVPWp6peRVLe+0EE/fj5p1RWPMe0GY2vgQO7h2Tf5GYjH/cfbu036m67c4Kr78jbO9DNbaY+MRa/1QdGdfYPlGzrb0Xda/nDuLH7MFR7fL99BkqQrOf+9rpcykO370fwuwMfZ+Gl8pM/2nmpj+8vI7vppbI3iico8aoW6oCUV3hes7xXeO9OxDqrjHn2mwm1eLI3CJY14k3f8M7NRA6upyu1dK59wVTxRIy9xCethDbuyzK1bdeoflRRzn9lo0FE5vnrkVlnimlmvWt2FDy1YdargEy9vzsmXrhRyIRGcVMcr7O8qJUhJIlQrqmtiQRv7N1vSssR+PslXTFWLBZxPFDUnH7unCC+44zWm0IQ98I771076S15ikHfsz0yW96Uj/qX3cAUbEHJGEGOki7t4Ih1w2IG4NBxg0qC7rLmDe93pFo2KDXXO4mMWoYBYvEmYQtqPd4nQjDDVym5+Mr5zVaQH5UObNPMH69yIApUU/XCXC7FkW6LEmgltRucU3KePBD5gvwOymwdpjm2R/OuyzizXVMI1X85oiCcdzBQzknARv/Oo3TOueNIAyhno2bITopkpPsSYLbsjD3mad+eJ1+TCRYllHU5Jx8fM1jEOVMIBf9AIznkwtJnwbNbwiLXNxFqU4kBFtC0nzYevuFGiaFwiOvdBW/nUob4kwWArxlwSohW9aMoDpWgbTrlAgTpwjK1YSq4mEsol9XdJErhPxVUiQvTgnSuwmCYGuJMKEmY2KtNuXpjlRgXnB9GQKl4CIM04oYJD1u7aOGQz59jlXIukQWfu747/+1AsBWHPmRJnEIdZEKP4Ekcc/Jc/xL5aTO91B9eL+Zfx06j6sbh9pmOhX19nbMFq5Vhrx7LBT6O932Cvi9nYOuZ6vdms/iDf2Bq5qS1br1LtmCtvbV891/WudpZaGuSpCa4bBzhrvbleczfbOI6bW5Zz9TaZ53pgYwJt/P79TwAAAP//a+Rl+/MDAAA=
    cosign.sigstore.dev/message: H4sIAAAAAAAA/wArAtT9H4sIAAAAAAAA/+xT3U7jPBDtdZ/C4vZTqENTCpG4KDTwBVqg/IWy2gtjJsFN/IPtQoL24VcJIWSRdheklVYr9dxkfHw8Z2Y06VmuelRypcEYJhLHEu0kz06fbmzHW2QD3K2tHieCxWDsekF41vk0MMZ40/OqL8b4/df1vM2O6/Vdb+ANvc1hB2+4w4HbQfjzVp/H0liiOxhrKe2vdL+7f9/cPwKi2BVow6TwEZXCWE2YsGY9IRZSAAV63dz3Ht1bsMTtpkzc+Whar0MoLCSa2WKvedjlYMkdscTvIiQIBx+BiKWm4OhlBo4hXGXgKC1jloGDu0YBLbWcWHpfBgiVJuYldBBR7EDLpaqJF0qZ5rC2VoetVyU/BpXJgoOwDXUO+pFRqM5laUYRCo1RXZkoUyuiCQcLur4l1JYDqjNxeffWVsW9De74Ay1X1UI5tJgljX8KxasBQqfB1EffmiNCTond4CA8RqeXu5NwDx0F84psiab76VPwNP//SN6Ezwu8N5rNwzoej2Z0PEtGweBZxA9B1J/ExTRKr661yk/ygz4O3etBK9UiG4reU8Ru8ii3Y5MWF9H+ZRLNbTi5VYf/Lbazwwd9Gu9mvFDeJLcn+WAw613Mz0Y7O+/LDo7HPy36IytS6uTtAqg9hwyoldpHX75WtGGJIHap4Qzi1+m1OCOXmrbvXg0bjaNr0Q+CajP81kr87b90hRVWWOHP43sAAAD//817TWkACgAAAQAA///P+EAmKwIAAA==
    cosign.sigstore.dev/signature: MEUCIQCfFdp6mxPsyLZHJBhb5x2wfvRmeJcqDKlbD7edIFIt4AIgT5FeblrQPydgid276LORnFOVRzzhc3vbXIKlMNKx8J0=
  name: enforce-rule-sample-profile-0
spec:
  match:
    kinds:
    - apiGroups:
      - apps
      - ""
      kinds:
      - Deployment
      - Service
    namespaces:
    - sample-ns
  parameters:
    action:
      mode: enforce
    constraintName: enforce-rule-sample-profile-0
    keyConfigs:
    - key:
        PEM: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5znfqEW3LfyMWkVXrpxOxG30I1X5
          jl7n/wWiZxWxtDskyTWFUgWYtILbpJ+j9lJqrPfBlmyp4LxtOx55Q/TYRA==
          -----END PUBLIC KEY-----
        name: enforce-rule-sample-profile-0
    objectSelector: []
    signatureRef:
      signatureResourceRef:
        name: signature-resource
        namespace: sample-ns
