apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ManifestIntegrityConstraint
metadata:
  name: enforce-rule-sample-profile-0
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Deployment
      - Service
    namespaces: []
  parameters:
    action:
      mode: enforce
    constraintName: enforce-rule-sample-profile-0
    keyConfigs:
    - key:
        PEM: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5znfqEW3LfyMWkVXrpxOxG30I1X5
          jl7n/wWiZxWxtDskyTWFUgWYtILbpJ+j9lJqrPfBlmyp4LxtOx55Q/TYRA==
          -----END PUBLIC KEY-----
        name: enforce-rule-sample-profile-0
    objectSelector: []
    signatureRef:
      signatureResourceRef:
        name: signature-resource
        namespace: ""
