apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cosign.sigstore.dev/message: H4sIAAAAAAAA/wCmAVn+H4sIAAAAAAAA/+yTz47aMBDGc85T+AVMHALLyuceethDpUq9D2Yapon/yDNBYp++SloCuy1FnNpKfBc7Hmd+nz/ZlfhUuehTRmYKrRbIun3VzZMzzdItd89bV3kI9BVZFkfwfXG3jDHmabWaRmPM+7Fe13VRr5rarDZNY5aFWdab9aZQ5n7U/RpYIBfG5BjlT/tu1d8f7j8RJPqCmSkGqw512VHYWfUZ84Eclh4FdiBgS6V62GLP40wpSGnRDVvMAQV5QbGiwALBoVUMPvWoIaVpa8rxGzqxak856m5giZ5eT/UA/vzLudgOyLKNsdMDlZzQjdgUs0x8PU2tejYTQSC3KJ/OS4w9Ool59mrVm4a3bJVa6/IyF0iJqzmcD5j6ePQY5N/KJ2PqyQFbVU9fBxrdfySWmI8v5EmsWv8Sjwdx+5cL79cSu2VV0KceBH+2vUhmVP+GcJ1xi6LU6bijXAwCFDDPnbUiDy1a1bo85r7HJBT1tMhVxxfR7dBHaxb1TP4R9u9Nne7eiTKT53v3tx/yQw899NCd+h4AAP//qf3VawAKAAABAAD//79cEISmAQAA
    cosign.sigstore.dev/signature: MEUCIHm70DovkQZ2pNN197QJqrRrARx+4eST42ByLPRgE6vUAiEA4xooUughEmWdxBi3Fih+sj7aig55KT7i7dV46Kz6zgI=
  creationTimestamp: null
  labels:
    signatureResource: "true"
  name: signature-resource
