apiVersion: v1
data:
  message: H4sIAAAAAAAA/wCmAVn+H4sIAAAAAAAA/+yTz47TMBDGe85T+AXcOGm7u/KZA4c9ICFxn7pDOsT/5JlU6j49SqBpd2GpegKkfhc7Hmd+nz/ZtYRcuxRyQWaKnRYounvRqwdnVq1rd09bVweI9BVZlkcIfnGzjDHmYb2eRmPM27HZNM2iWa8aszGmNY8L0zaPm3ahzO2o2zWwQFkYU1KSP+27Vn97uP9EkOkLFqYUrTo0VU9xZ9VnLAdyWAUU2IGArZTysEXP40wpyHnZD1ssEQV5SammyALRoVUMIXvUkPO0NZf0DZ1YtaeSdD+wpEAvp3qEcP7lXOwGZNmm1OuBKs7oRmxORSa+nqZWPZmJIFA6lE/nJUaPTlKZvVr1quE1W5XWurrMBXLmeg7nA2afjgGj/Fv5FMyeHLBVzfR1oNH9R2JJ5fhMgcSqzS/xBBC3f77w/l5i16wKhuxB8Gfbi2RG+VeE9xnXKEqdjjvKpShAEcvcWSsK0KFVnStj7nvMQklPi1z3fBHdDkOyZtnM5B9h/97U6e6dKDN5vnd/+yHfddddd92o7wEAAP//PLXxJAAKAAABAAD//1R1zVemAQAA
  signature: MEYCIQCTlsTNPrXoEXsxSdeKJUbyE2kXJo85DL7z8ZIXI8juwQIhANCz+cgInbp18UzVXoGJzWJNJQXgo+zqAOof9TEAnNkm
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    signatureResource: "true"
  name: signature-resource
