apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cosign.sigstore.dev/message: H4sIAAAAAAAA/wDJATb+H4sIAAAAAAAA/+xTTWvbTBD2Wb9iyX3tVazYRtf3PfSQQumh9/FqLE+zX+yMDG7pfy9SXEU2aYNpoRT8XHaHmXk+JHYhPi1s9CkjM4VWC2TdftHrarveNHaz2ZWw8BBohyzzI3g3uxrGGLOqquE0xlyeZbVaz8pqadYP69WyMjNzf2+W5UyZ66WuR8cCeWZMjlF+NfdW/zLcPwJI9AkzUwy1OpRFAwK1+vqteKLQ1Oq/GHbUvodUeBQYmoVSDrbouL8pBSnNn7ot5oCCPKe4oMACwWKtGHxyqCGlYZSCYJtJjrwndE0/y9QGkC7jR+TY5X7pTnKHd8NCyvEzWrkgCuDPuPXpagevHlJRaK2LaTBIiReH8hTqf0wuHj0G+ROprjPZvGhzQturZUyOLHCtyqE6UG/6HbHEfHwkT1Krh0IpRodWYn526EHs/nFieTA9Sk50npuv2xT0yYHgiXPyNXq4M/o3BH4modSPoD1sDAIUMI+0WkFuJyJaaTsp2CEmRWFHgeQ4Nmz0HkIzXdsC78eSPLRYq27bBenqPiK/GD37Oa8FiVnOHI2uP8QstdqY4m8/2xtuuOGG38b3AAAA///yFqV9AAoAAAEAAP//Oocb3MkBAAA=
    cosign.sigstore.dev/signature: MEYCIQC8l+tI2XTdSu581Vh+bCG7g2eqyMOXYmGUix0Fdsc7swIhAM47AGtdYoIP1cWj22jiQULHolql7FGbNU1pseqBs3M7
  creationTimestamp: null
  labels:
    signatureResource: "true"
  name: signature-resource
