apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cosign.sigstore.dev/message: H4sIAAAAAAAA/wCnAVj+H4sIAAAAAAAA/+yTz47TMBDGc85T+AXcOJu0u/KZA4c9ICFxn7pDOiT+I8+kUvfpUQJNuwtL1RMg9bvY8Tjz+/zJrsSnykWfMjJT6LRA1t2LbjbONA/uYfe0dZWHQF+RZXUEPxQ3yxhjNm07j8aYt2O9ruuibpvatI9N064L81A/bjaFMrejbtfIArkwJscof9p3rf72cP+JINEXzEwxWHWoy57CzqrPmA/ksPQosAMBWyo1wBYHnmZKQUqrftxiDijIK4oVBRYIDq1i8GlADSnNW1OO39CJVXvKUfcjS/T0cqoH8OdfzsVuRJZtjL0eqeSEbsKmmGXm63lq1ZOZCQK5Q/l0XmIc0EnMi1erXjW8ZqvUWpeXuUBKXC3hfMA0xKPHIP9WPhnTQA7Yqnr+OtDk/iOxxHx8Jk9i1fqXeDyI2z9feH8vsWtWBX0aQPBn24tkJg2vCO8zrlGUOh13kotBgALmpbNW5KFDqzqXp9z3mISinhe56vkiuh36aM2qXsg/wv69qdPdO1EW8nLv/vZDvuuuu+66Ud8DAAD//ywX9IYACgAAAQAA//8IklRZpwEAAA==
    cosign.sigstore.dev/signature: MEYCIQC993JLx2OgDwoR3eYyrMpsjziM9Ffa0I/okSchWMSdUwIhAMkCKG87eEOvRncAfpMNrcthJsAg0bAvOA0RKwkiwyMb
  creationTimestamp: null
  labels:
    signatureResource: "true"
  name: signature-resource
